"""add stage idempotency attempt constraint

Revision ID: 1b105fb342a2
Revises: 05525128ce26
Create Date: 2026-08-04 20:43:32.354896
"""

from collections.abc import Sequence

from alembic import op

revision: str = "1b105fb342a2"
down_revision: str | Sequence[str] | None = "05525128ce26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_stage_idempotency_attempt", "stage_executions", ["idempotency_key", "attempt"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_stage_idempotency_attempt", "stage_executions", type_="unique")
    # ### end Alembic commands ###
