"""Framework-independent domain package."""

from auto_video_sub_domain.errors import (
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    DomainError,
    NotFoundError,
    QuotaExceededError,
    ValidationError,
)
from auto_video_sub_domain.ids import new_uuid7
from auto_video_sub_domain.media import (
    Artifact,
    ArtifactKind,
    ArtifactState,
    MediaAsset,
    MediaLimits,
    MediaProbe,
    MediaStatus,
    RetentionClass,
    UploadIntent,
    UploadState,
    safe_display_name,
    validate_probe,
)
from auto_video_sub_domain.projects import Project, ProjectLifecycle, User, validate_project_title
from auto_video_sub_domain.speech import (
    DurationFitAction,
    DurationFitDecision,
    DurationFitPolicy,
    SpeechAttempt,
    SpeechAttemptOutcome,
    SpeechSegmentStatus,
    SpeechStatus,
    SpeechTextOrigin,
    decide_duration_fit,
)
from auto_video_sub_domain.subtitle_style import (
    SubtitleAlignment,
    SubtitleStyleDraft,
    SubtitleStyleVersion,
)
from auto_video_sub_domain.transcript import (
    ConsolidatedSegment,
    OcrObservation,
    SourceRevision,
    SourceRevisionOrigin,
    SubtitleRegion,
    SubtitleSegment,
    TranscriptStatus,
    consolidate_observations,
    normalize_ocr_text,
)
from auto_video_sub_domain.translation import (
    ContextEntity,
    ContextVersion,
    TonePreset,
    TranslationBatchPlan,
    TranslationFinding,
    TranslationPolicyVersion,
    TranslationRevision,
    TranslationRevisionOrigin,
    TranslationStatus,
    contains_han,
    plan_translation_batches,
    validate_translation_items,
)

__all__ = [
    "Artifact",
    "ArtifactKind",
    "ArtifactState",
    "AuthenticationError",
    "AuthorizationError",
    "ConflictError",
    "ConsolidatedSegment",
    "ContextEntity",
    "ContextVersion",
    "DomainError",
    "DurationFitAction",
    "DurationFitDecision",
    "DurationFitPolicy",
    "MediaAsset",
    "MediaLimits",
    "MediaProbe",
    "MediaStatus",
    "NotFoundError",
    "OcrObservation",
    "Project",
    "ProjectLifecycle",
    "QuotaExceededError",
    "RetentionClass",
    "SourceRevision",
    "SourceRevisionOrigin",
    "SpeechAttempt",
    "SpeechAttemptOutcome",
    "SpeechSegmentStatus",
    "SpeechStatus",
    "SpeechTextOrigin",
    "SubtitleAlignment",
    "SubtitleRegion",
    "SubtitleSegment",
    "SubtitleStyleDraft",
    "SubtitleStyleVersion",
    "TonePreset",
    "TranscriptStatus",
    "TranslationBatchPlan",
    "TranslationFinding",
    "TranslationPolicyVersion",
    "TranslationRevision",
    "TranslationRevisionOrigin",
    "TranslationStatus",
    "UploadIntent",
    "UploadState",
    "User",
    "ValidationError",
    "__version__",
    "consolidate_observations",
    "contains_han",
    "decide_duration_fit",
    "new_uuid7",
    "normalize_ocr_text",
    "plan_translation_batches",
    "safe_display_name",
    "validate_probe",
    "validate_project_title",
    "validate_translation_items",
]

__version__ = "0.1.0"
